version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cryofly-backend
    depends_on:
      - redis
    volumes:
      - type: volume
        source: sqlite_data
        target: /instance
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: cryofly-frontend
    ports:
      - 5000:80
    depends_on:
      - redis
  redis:
    image: redis:7.0.5-alpine
    volumes:
      - redis:/data

volumes:
  redis:
  sqlite_data: